### PR TITLE
fix always scrollToTop, introduce slate heading anchors UUID based

### PR DESCRIPTION
**Pull request by nileshgulia1**

### CODE REVIEW

**Comment by avoinea** [comment]
@nileshgulia1 Thank you for this PR.

Still, the scroll seems not to work properly when you're opening in new tab. See attached video:

[open-in-new-tab.webm](https://user-images.githubusercontent.com/323385/215157591-f4140f3f-94e8-4cde-b69b-04284dd0c2ff.webm)

**Review by avoinea — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by nileshgulia1** [comment]
@avoinea Sorry, The customization paths were incorrect. Fixed in [26624ae](https://github.com/eea/volto-eea-website-policy/pull/35/commits/26624aeb475c182dd0779f32bc0d42ec671d0b38)

**Comment by avoinea** [comment]
@nileshgulia1 Can you please move this to a dedicated add-on? This feature will be needed for sure to be used also with other EEA websites. 

We will also have to extend it's functionality to add support for accordion / tabs to open closed accordion / tab pane if the heading is within there.

**Comment by nileshgulia1** [comment]
@avoinea New addon created https://github.com/eea/volto-anchors/pull/1
The slate heading anchors are now based on sluggified titles. TOC blocks are also aware of title slugs when navigating along with a fix for override_toc.

**Pull request closed without merging**
